// -------------------------------------------------------------
// 
// File Name: hdlsrc\DNN\MATLAB_Function.v
// Created: 2024-09-19 22:24:12
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function
// Source Path: DNN/DNNModel/MATLAB Function
// Hierarchy Level: 1
// Model version: 1.53
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function
          (u,
           Thresh,
           yprd);


  input   signed [15:0] u;  // sfix16_En14
  input   Thresh;  // ufix1_En1
  output  yprd;  // ufix1


  reg  yprd_1;  // ufix1
  reg signed [15:0] cast;  // sfix16_En14


  always @(Thresh, u) begin
    cast = {2'b0, {Thresh, 13'b0000000000000}};
    if (u > cast) begin
      yprd_1 = 1'b1;
    end
    else begin
      yprd_1 = 1'b0;
    end
  end



  assign yprd = yprd_1;

endmodule  // MATLAB_Function

