// -------------------------------------------------------------
// 
// File Name: hdlsrc\MyRegModel_Simulink\LinearRegModel.v
// Created: 2024-09-15 07:00:46
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LinearRegModel
// Source Path: MyRegModel_Simulink/LinearRegModel
// Hierarchy Level: 0
// Model version: 1.54
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LinearRegModel
          (In1,
           In2,
           In3,
           In4,
           In5,
           ypre_simulink);


  input   signed [30:0] In1;  // sfix31_En12
  input   signed [20:0] In2;  // sfix21_En15
  input   signed [22:0] In3;  // sfix23_En17
  input   signed [15:0] In4;  // sfix16_En11
  input   signed [36:0] In5;  // sfix37_En18
  output  [23:0] ypre_simulink;  // ufix24_En3


  wire signed [61:0] Gain4_out1;  // sfix62_En37
  wire signed [41:0] Gain_out1;  // sfix42_En17
  wire signed [76:0] Add_stage2_add_cast;  // sfix77_En50
  wire signed [76:0] Add_stage2_add_cast_1;  // sfix77_En50
  wire signed [76:0] Add_stage2_add_temp;  // sfix77_En50
  wire signed [62:0] Add_op_stage1;  // sfix63_En37
  wire signed [45:0] Gain1_out1;  // sfix46_En22
  wire signed [76:0] Add_stage3_add_cast;  // sfix77_En50
  wire signed [76:0] Add_stage3_add_cast_1;  // sfix77_En50
  wire signed [76:0] Add_stage3_add_temp;  // sfix77_En50
  wire signed [63:0] Add_op_stage2;  // sfix64_En37
  wire signed [31:0] Gain2_out1;  // sfix32_En15
  wire signed [76:0] Add_stage4_add_cast;  // sfix77_En50
  wire signed [76:0] Add_stage4_add_cast_1;  // sfix77_En50
  wire signed [76:0] Add_stage4_add_temp;  // sfix77_En50
  wire signed [64:0] Add_op_stage3;  // sfix65_En37
  wire signed [73:0] Gain3_out1;  // sfix74_En50
  wire signed [76:0] Add_stage5_add_cast;  // sfix77_En50
  wire signed [76:0] Add_stage5_add_cast_1;  // sfix77_En50
  wire signed [76:0] Add_stage5_add_temp;  // sfix77_En50
  wire signed [78:0] Add_op_stage4;  // sfix79_En50
  wire signed [31:0] Constant_out1;  // sfix32_En9
  wire signed [76:0] Add_stage6_add_cast;  // sfix77_En50
  wire signed [76:0] Add_stage6_add_cast_1;  // sfix77_En50
  wire signed [76:0] Add_stage6_add_temp;  // sfix77_En50


  assign Gain4_out1 = 31'sb0101011001001010110001001010011 * In1;


  assign Gain_out1 = 21'sb010100001000100011100 * In2;


  assign Add_stage2_add_cast = {{2{Gain4_out1[61]}}, {Gain4_out1, 13'b0000000000000}};
  assign Add_stage2_add_cast_1 = {{2{Gain_out1[41]}}, {Gain_out1, 33'b000000000000000000000000000000000}};
  assign Add_stage2_add_temp = Add_stage2_add_cast + Add_stage2_add_cast_1;
  assign Add_op_stage1 = Add_stage2_add_temp[75:13];



  assign Gain1_out1 = 23'sb01110100111101101111101 * In3;


  assign Add_stage3_add_cast = {Add_op_stage1[62], {Add_op_stage1, 13'b0000000000000}};
  assign Add_stage3_add_cast_1 = {{3{Gain1_out1[45]}}, {Gain1_out1, 28'b0000000000000000000000000000}};
  assign Add_stage3_add_temp = Add_stage3_add_cast + Add_stage3_add_cast_1;
  assign Add_op_stage2 = Add_stage3_add_temp[76:13];



  assign Gain2_out1 = 16'sb0101010101100001 * In4;


  assign Add_stage4_add_cast = {Add_op_stage2, 13'b0000000000000};
  assign Add_stage4_add_cast_1 = {{10{Gain2_out1[31]}}, {Gain2_out1, 35'b00000000000000000000000000000000000}};
  assign Add_stage4_add_temp = Add_stage4_add_cast + Add_stage4_add_cast_1;
  assign Add_op_stage3 = {Add_stage4_add_temp[76], Add_stage4_add_temp[76:13]};



  assign Gain3_out1 = 37'sh0F43CED491 * In5;


  assign Add_stage5_add_cast = {Add_op_stage3[63:0], 13'b0000000000000};
  assign Add_stage5_add_cast_1 = {{3{Gain3_out1[73]}}, Gain3_out1};
  assign Add_stage5_add_temp = Add_stage5_add_cast + Add_stage5_add_cast_1;
  assign Add_op_stage4 = {{2{Add_stage5_add_temp[76]}}, Add_stage5_add_temp};



  assign Constant_out1 = 32'sb10101111110001110100010010001001;


  assign Add_stage6_add_cast = Add_op_stage4[76:0];
  assign Add_stage6_add_cast_1 = {{4{Constant_out1[31]}}, {Constant_out1, 41'b00000000000000000000000000000000000000000}};
  assign Add_stage6_add_temp = Add_stage6_add_cast + Add_stage6_add_cast_1;
  assign ypre_simulink = Add_stage6_add_temp[70:47];


endmodule  // LinearRegModel

